data_ingestion:
  raw_data_path: data/raw/IBM.csv

data_preprocessing:
  processed_data_path: data/processed/processed_data.csv

feature_engineering:
  featured_data_path: data/features/featured_data.csv

model_training:
  window_size: 60
  epochs: 50
  batch_size: 32

artifacts:
  scaler_path: artifacts/scaler.pkl

models:
  lstm_model_path: models/lstm.keras

model_evaluation:
  model_path: models/lstm.keras
  evaluation_path: artifacts/evaluation.json