data_ingestion:
  raw_data_path: data/raw/IBM.csv

data_preprocessing:
  processed_data_path: data/processed/processed_data.csv

feature_engineering:
  featured_data_path: data/features/featured_data.csv